title: Hasan Gök
description: Bir Garip Bilgisayar Mühendisi

url: http://www.hasangok.com.tr
baseurl: ""
paginate_path: "blog/page:num/"
permalink: /:year/:month/:day/:title.html

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 5
paginate_path: "/page/:num"
excerpt_separator: "<!--more-->"

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Contact
   url: /contact

social:
   github: hasangok
   twitter: hasangok
   facebook: hasangok
   email: hasangok@gmail.com

google_analytics: "UA-37356879-1"
